# Dockerfile.consumer
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY weather_consumer.py .
CMD ["python", "weather_consumer.py"]
